#!/bin/bash


# OUTPUT_DIR=/home/bryan/expr/brain_tumor/2023-08-06/preprocess-subjects-skull-crop
# python mgmt/tasks/preprocess_subjects.py \
# --extension .skull-crop-64.nii \
# OUTPUT_DIR $OUTPUT_DIR \
# SEED_EVERYTHING 1 \
# PATCH_BASED_TRAINER.LABEL_SAMPLER.patch_size "[64, 64, 64]" \
# PREPROCESS.TO_CANONICAL_ENABLED True \
# AUGMENT.RANDOM_AFFINE_ENABLED False \
# AUGMENT.RANDOM_GAMMA_ENABLED False \
# AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
# AUGMENT.RANDOM_MOTION_ENABLED False \
# AUGMENT.RANDOM_NOISE_ENABLED False \
# PREPROCESS.RESCALE_INTENSITY_ENABLED True

# OUTPUT_DIR=/home/bryan/expr/brain_tumor/2023-08-08/preprocess-subjects-crop-64
# python mgmt/tasks/preprocess_subjects.py \
# --mode pickle-subjects \
# --pickle-save-path $OUTPUT_DIR \
# OUTPUT_DIR $OUTPUT_DIR/logs \
# SEED_EVERYTHING 1 \
# PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
# PREPROCESS.TO_CANONICAL_ENABLED True \
# AUGMENT.RANDOM_AFFINE_ENABLED False \
# AUGMENT.RANDOM_GAMMA_ENABLED False \
# AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
# AUGMENT.RANDOM_MOTION_ENABLED False \
# AUGMENT.RANDOM_NOISE_ENABLED False \
# PREPROCESS.RESCALE_INTENSITY_ENABLED True

# OUTPUT_DIR=/home/bryan/expr/brain_tumor/2023-08-08/preprocess-subjects-crop-64-t1c
# python mgmt/tasks/preprocess_subjects.py \
# --mode pickle-subjects \
# --modalities t1c \
# --pickle-save-path $OUTPUT_DIR \
# OUTPUT_DIR $OUTPUT_DIR/logs \
# SEED_EVERYTHING 1 \
# PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
# PREPROCESS.TO_CANONICAL_ENABLED True \
# AUGMENT.RANDOM_AFFINE_ENABLED False \
# AUGMENT.RANDOM_GAMMA_ENABLED False \
# AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
# AUGMENT.RANDOM_MOTION_ENABLED False \
# AUGMENT.RANDOM_NOISE_ENABLED False \
# PREPROCESS.RESCALE_INTENSITY_ENABLED True

# OUTPUT_DIR=/home/bryan/expr/brain_tumor/2023-08-08/preprocess-subjects-resample-1.8-crop-64-t1c
# python mgmt/tasks/preprocess_subjects.py \
# --mode pickle-subjects \
# --modalities t1c \
# --pickle-save-path $OUTPUT_DIR \
# OUTPUT_DIR $OUTPUT_DIR/logs \
# SEED_EVERYTHING 1 \
# PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
# PREPROCESS.TO_CANONICAL_ENABLED True \
# AUGMENT.RANDOM_AFFINE_ENABLED False \
# AUGMENT.RANDOM_GAMMA_ENABLED False \
# AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
# AUGMENT.RANDOM_MOTION_ENABLED False \
# AUGMENT.RANDOM_NOISE_ENABLED False \
# PREPROCESS.RESCALE_INTENSITY_ENABLED True \
# PREPROCESS.RESAMPLE_ENABLED True \
# PREPROCESS.RESAMPLE.target 1.8

# OUTPUT_DIR=/home/bryan/expr/brain_tumor/preprocess-subjects/resample-1.8-crop-64
# python mgmt/tasks/preprocess_subjects.py \
# --mode pickle-subjects \
# --pickle-save-path $OUTPUT_DIR \
# OUTPUT_DIR $OUTPUT_DIR/logs \
# SEED_EVERYTHING 1 \
# PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
# PREPROCESS.TO_CANONICAL_ENABLED True \
# PREPROCESS.RESAMPLE_ENABLED True \
# PREPROCESS.RESAMPLE.target 1.8 \
# PREPROCESS.SKULL_CROP_TRANSFORM_ENABLED True \
# PREPROCESS.ADD_PATCH_SAMPLER_PROB_MAP_ENABLED True \
# AUGMENT.RANDOM_AFFINE_ENABLED False \
# AUGMENT.RANDOM_GAMMA_ENABLED False \
# AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
# AUGMENT.RANDOM_MOTION_ENABLED False \
# AUGMENT.RANDOM_NOISE_ENABLED False \
# PREPROCESS.RESCALE_INTENSITY_ENABLED True

# OUTPUT_DIR=/home/bryan/expr/brain_tumor/preprocess-subjects/resample-1.8-crop-64-fla
# python mgmt/tasks/preprocess_subjects.py \
# --mode pickle-subjects \
# --modalities fla \
# --pickle-save-path $OUTPUT_DIR \
# OUTPUT_DIR $OUTPUT_DIR/logs \
# SEED_EVERYTHING 1 \
# PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
# PREPROCESS.TO_CANONICAL_ENABLED True \
# PREPROCESS.RESAMPLE_ENABLED True \
# PREPROCESS.RESAMPLE.target 1.8 \
# PREPROCESS.SKULL_CROP_TRANSFORM_ENABLED True \
# PREPROCESS.SKULL_CROP_TRANSFORM.mask_image_name fla \
# PREPROCESS.ADD_PATCH_SAMPLER_PROB_MAP_ENABLED True \
# AUGMENT.RANDOM_AFFINE_ENABLED False \
# AUGMENT.RANDOM_GAMMA_ENABLED False \
# AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
# AUGMENT.RANDOM_MOTION_ENABLED False \
# AUGMENT.RANDOM_NOISE_ENABLED False \
# PREPROCESS.RESCALE_INTENSITY_ENABLED True

# OUTPUT_DIR=/home/bryan/expr/brain_tumor/preprocess-subjects/resample-1.8-crop-64-t1w
# python mgmt/tasks/preprocess_subjects.py \
# --mode pickle-subjects \
# --modalities t1w \
# --pickle-save-path $OUTPUT_DIR \
# OUTPUT_DIR $OUTPUT_DIR/logs \
# SEED_EVERYTHING 1 \
# PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
# PREPROCESS.TO_CANONICAL_ENABLED True \
# PREPROCESS.RESAMPLE_ENABLED True \
# PREPROCESS.RESAMPLE.target 1.8 \
# PREPROCESS.SKULL_CROP_TRANSFORM_ENABLED True \
# PREPROCESS.SKULL_CROP_TRANSFORM.mask_image_name t1w \
# PREPROCESS.ADD_PATCH_SAMPLER_PROB_MAP_ENABLED True \
# AUGMENT.RANDOM_AFFINE_ENABLED False \
# AUGMENT.RANDOM_GAMMA_ENABLED False \
# AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
# AUGMENT.RANDOM_MOTION_ENABLED False \
# AUGMENT.RANDOM_NOISE_ENABLED False \
# PREPROCESS.RESCALE_INTENSITY_ENABLED True

# OUTPUT_DIR=/home/bryan/expr/brain_tumor/preprocess-subjects/resample-1.8-crop-64-t2w
# python mgmt/tasks/preprocess_subjects.py \
# --mode pickle-subjects \
# --modalities t2w \
# --pickle-save-path $OUTPUT_DIR \
# OUTPUT_DIR $OUTPUT_DIR/logs \
# SEED_EVERYTHING 1 \
# PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
# PREPROCESS.TO_CANONICAL_ENABLED True \
# PREPROCESS.RESAMPLE_ENABLED True \
# PREPROCESS.RESAMPLE.target 1.8 \
# PREPROCESS.SKULL_CROP_TRANSFORM_ENABLED True \
# PREPROCESS.SKULL_CROP_TRANSFORM.mask_image_name t2w \
# PREPROCESS.ADD_PATCH_SAMPLER_PROB_MAP_ENABLED True \
# AUGMENT.RANDOM_AFFINE_ENABLED False \
# AUGMENT.RANDOM_GAMMA_ENABLED False \
# AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
# AUGMENT.RANDOM_MOTION_ENABLED False \
# AUGMENT.RANDOM_NOISE_ENABLED False \
# PREPROCESS.RESCALE_INTENSITY_ENABLED True

# OUTPUT_DIR=/home/bryan/expr/brain_tumor/preprocess-subjects/resample-1.5-crop-64
# python mgmt/tasks/preprocess_subjects.py \
# --mode pickle-subjects \
# --pickle-save-path $OUTPUT_DIR \
# OUTPUT_DIR $OUTPUT_DIR/logs \
# SEED_EVERYTHING 1 \
# PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
# PREPROCESS.TO_CANONICAL_ENABLED True \
# PREPROCESS.RESAMPLE_ENABLED True \
# PREPROCESS.RESAMPLE.target 1.5 \
# PREPROCESS.SKULL_CROP_TRANSFORM_ENABLED True \
# PREPROCESS.ADD_PATCH_SAMPLER_PROB_MAP_ENABLED True \
# AUGMENT.RANDOM_AFFINE_ENABLED False \
# AUGMENT.RANDOM_GAMMA_ENABLED False \
# AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
# AUGMENT.RANDOM_MOTION_ENABLED False \
# AUGMENT.RANDOM_NOISE_ENABLED False \
# PREPROCESS.RESCALE_INTENSITY_ENABLED True

# OUTPUT_DIR=/home/bryan/expr/brain_tumor/preprocess-subjects/resample-1.2-crop-64
# python mgmt/tasks/preprocess_subjects.py \
# --mode pickle-subjects \
# --pickle-save-path $OUTPUT_DIR \
# OUTPUT_DIR $OUTPUT_DIR/logs \
# SEED_EVERYTHING 1 \
# PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
# PREPROCESS.TO_CANONICAL_ENABLED True \
# PREPROCESS.RESAMPLE_ENABLED True \
# PREPROCESS.RESAMPLE.target 1.2 \
# PREPROCESS.SKULL_CROP_TRANSFORM_ENABLED True \
# PREPROCESS.ADD_PATCH_SAMPLER_PROB_MAP_ENABLED True \
# AUGMENT.RANDOM_AFFINE_ENABLED False \
# AUGMENT.RANDOM_GAMMA_ENABLED False \
# AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
# AUGMENT.RANDOM_MOTION_ENABLED False \
# AUGMENT.RANDOM_NOISE_ENABLED False \
# PREPROCESS.RESCALE_INTENSITY_ENABLED True

OUTPUT_DIR=/home/bryan/expr/brain_tumor/preprocess-subjects-v2/resample-2.0-crop-64
python mgmt/tasks/preprocess_subjects.py \
--mode pickle-subjects \
--pickle-save-path $OUTPUT_DIR \
OUTPUT_DIR $OUTPUT_DIR/logs \
SEED_EVERYTHING 1 \
PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
PREPROCESS.TO_CANONICAL_ENABLED True \
PREPROCESS.RESAMPLE_ENABLED True \
PREPROCESS.RESAMPLE.target 2.0 \
PREPROCESS.SKULL_CROP_TRANSFORM_ENABLED True \
PREPROCESS.ADD_PATCH_SAMPLER_PROB_MAP_ENABLED True \
AUGMENT.RANDOM_AFFINE_ENABLED False \
AUGMENT.RANDOM_GAMMA_ENABLED False \
AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
AUGMENT.RANDOM_MOTION_ENABLED False \
AUGMENT.RANDOM_NOISE_ENABLED False \
PREPROCESS.RESCALE_INTENSITY_ENABLED True

OUTPUT_DIR=/home/bryan/expr/brain_tumor/preprocess-subjects-v2/resample-1.5-crop-64
python mgmt/tasks/preprocess_subjects.py \
--mode pickle-subjects \
--pickle-save-path $OUTPUT_DIR \
OUTPUT_DIR $OUTPUT_DIR/logs \
SEED_EVERYTHING 1 \
PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
PREPROCESS.TO_CANONICAL_ENABLED True \
PREPROCESS.RESAMPLE_ENABLED True \
PREPROCESS.RESAMPLE.target 1.5 \
PREPROCESS.SKULL_CROP_TRANSFORM_ENABLED True \
PREPROCESS.ADD_PATCH_SAMPLER_PROB_MAP_ENABLED True \
AUGMENT.RANDOM_AFFINE_ENABLED False \
AUGMENT.RANDOM_GAMMA_ENABLED False \
AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
AUGMENT.RANDOM_MOTION_ENABLED False \
AUGMENT.RANDOM_NOISE_ENABLED False \
PREPROCESS.RESCALE_INTENSITY_ENABLED True

OUTPUT_DIR=/home/bryan/expr/brain_tumor/preprocess-subjects-v2/resample-1.2-crop-64
python mgmt/tasks/preprocess_subjects.py \
--mode pickle-subjects \
--pickle-save-path $OUTPUT_DIR \
OUTPUT_DIR $OUTPUT_DIR/logs \
SEED_EVERYTHING 1 \
PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
PREPROCESS.TO_CANONICAL_ENABLED True \
PREPROCESS.RESAMPLE_ENABLED True \
PREPROCESS.RESAMPLE.target 1.2 \
PREPROCESS.SKULL_CROP_TRANSFORM_ENABLED True \
PREPROCESS.ADD_PATCH_SAMPLER_PROB_MAP_ENABLED True \
AUGMENT.RANDOM_AFFINE_ENABLED False \
AUGMENT.RANDOM_GAMMA_ENABLED False \
AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
AUGMENT.RANDOM_MOTION_ENABLED False \
AUGMENT.RANDOM_NOISE_ENABLED False \
PREPROCESS.RESCALE_INTENSITY_ENABLED True

OUTPUT_DIR=/home/bryan/expr/brain_tumor/preprocess-subjects-v2/crop-64
python mgmt/tasks/preprocess_subjects.py \
--mode pickle-subjects \
--pickle-save-path $OUTPUT_DIR \
OUTPUT_DIR $OUTPUT_DIR/logs \
SEED_EVERYTHING 1 \
PATCH_BASED_TRAINER.WEIGHTED_SAMPLER.patch_size "[64, 64, 64]" \
PREPROCESS.TO_CANONICAL_ENABLED True \
PREPROCESS.RESAMPLE_ENABLED False \
PREPROCESS.SKULL_CROP_TRANSFORM_ENABLED True \
PREPROCESS.ADD_PATCH_SAMPLER_PROB_MAP_ENABLED True \
AUGMENT.RANDOM_AFFINE_ENABLED False \
AUGMENT.RANDOM_GAMMA_ENABLED False \
AUGMENT.RANDOM_BIAS_FIELD_ENABLED False \
AUGMENT.RANDOM_MOTION_ENABLED False \
AUGMENT.RANDOM_NOISE_ENABLED False \
PREPROCESS.RESCALE_INTENSITY_ENABLED True